name: MLflow CI Pipeline 

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies (pip)
      run: |
        pip install --upgrade pip
        pip install \
          mlflow \
          dagshub \
          scikit-learn \
          pandas \
          matplotlib \
          seaborn

    - name: Configure MLflow Tracking (DAGsHub)
      env:
        DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_USER_TOKEN }}
      run: |
        echo "MLFLOW_TRACKING_URI=https://dagshub.com/${DAGSHUB_USERNAME}/Workflow-CI-Customer-Churn.mlflow" >> $GITHUB_ENV
        echo "MLFLOW_TRACKING_USERNAME=${DAGSHUB_USERNAME}" >> $GITHUB_ENV
        echo "MLFLOW_TRACKING_PASSWORD=${DAGSHUB_USER_TOKEN}" >> $GITHUB_ENV

    - name: Run MLflow Project
      run: |
        cd MLProject
        mlflow run . --env-manager=local | tee mlflow_output.txt
        RUN_ID=$(grep -oE 'Run ID: [a-f0-9]+' mlflow_output.txt | awk '{print $3}')
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

    - name: Build Docker Image
      run: |
        mlflow models build-docker \
          -m runs:/$RUN_ID/RandomForest_Baseline_Model \
          -n customer-churn-model

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Image
      run: |
        docker tag customer-churn-model ${{ secrets.DOCKERHUB_USERNAME }}/customer-churn-model:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/customer-churn-model:latest
