name: MLflow CI Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow dagshub scikit-learn pandas matplotlib seaborn

      - name: Configure MLflow Tracking (DAGsHub)
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_USER_TOKEN }}
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/${DAGSHUB_USERNAME}/Workflow-CI-Customer-Churn.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=${DAGSHUB_USERNAME}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${DAGSHUB_USER_TOKEN}" >> $GITHUB_ENV

      - name: Run MLflow Project & Capture RUN_ID
        run: |
          cd MLProject

          mlflow run . --env-manager=local

          python - << 'EOF'
          import mlflow, os

          client = mlflow.tracking.MlflowClient()
          runs = client.search_runs(
              experiment_ids=["0"],
              order_by=["start_time DESC"],
              max_results=1
          )

          if not runs:
              raise RuntimeError("No MLflow runs found")

          run_id = runs[0].info.run_id
          print("RUN_ID =", run_id)

          with open(os.environ["GITHUB_ENV"], "a") as f:
              f.write(f"RUN_ID={run_id}\n")
          EOF

      - name: Debug RUN_ID
        run: echo "RUN_ID=$RUN_ID"

      - name: Build Docker Image
        run: |
          mlflow models build-docker \
            -m runs:/$RUN_ID/RandomForest_Baseline_Model \
            -n customer-churn-model

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        run: |
          docker tag customer-churn-model ${{ secrets.DOCKERHUB_USERNAME }}/customer-churn-model:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/customer-churn-model:latest
