name: MLflow CI Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow dagshub scikit-learn pandas matplotlib seaborn

      - name: Configure MLflow Tracking (DAGsHub)
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_USER_TOKEN }}
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/${DAGSHUB_USERNAME}/Workflow-CI-Customer-Churn.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=${DAGSHUB_USERNAME}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${DAGSHUB_USER_TOKEN}" >> $GITHUB_ENV

      - name: Run MLflow Project & Capture RUN_ID
        env:
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ env.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ env.MLFLOW_TRACKING_PASSWORD }}
        run: |
          cd MLProject

          set -e
          echo "Running MLflow project..."
          OUTPUT=$(mlflow run . --env-manager=local 2>&1 | tee /tmp/mlflow_run.log)

          RUN_ID=$(echo "$OUTPUT" | grep -oE "run with ID '[0-9a-f]+'" | head -n 1 | sed -E "s/.*'([0-9a-f]+)'.*/\1/")

          if [ -z "$RUN_ID" ]; then
            echo "RUN_ID gagal dideteksi dari log. Ini isi log:"
            cat /tmp/mlflow_run.log
            exit 1
          fi

          echo "Captured RUN_ID=$RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Debug RUN_ID
        run: |
          echo "RUN_ID=$RUN_ID"
          test -n "$RUN_ID"

      - name: Upload training artifacts
        uses: actions/upload-artifact@v4
        with:
          name: training-artifacts
          path: MLProject/artifacts/

      - name: Build Docker Image from MLflow Model
        env:
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ env.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ env.MLFLOW_TRACKING_PASSWORD }}
        run: |
          echo "Building docker from: runs:/$RUN_ID/model"
          mlflow models build-docker -m "runs:/$RUN_ID/model" -n customer-churn-model

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag & Push Docker Image
        run: |
          docker tag customer-churn-model ${{ secrets.DOCKERHUB_USERNAME }}/customer-churn-model:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/customer-churn-model:latest
